apiVersion: v1
kind: Secret
metadata:
  name: mysql-{{ include "ghost-k8s.name" . }}
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_DATABASE: mysql_ghost-k8s # todo refactor. .Chart.Name is overriden by the parent chart.
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: spiritofbrogan-com-tls # todo refactor
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crtBase64 | quote }}
  tls.key: {{ .Values.tls.keyBase64 | quote }}
