apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost-k8s.name" . }}-static-ghost
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  volumeName: pvc-7aa7e7b5-be0c-4231-a900-68913ccf7f34 # Added to existing cluster pv/pvc maintenance.
  resources:
    requests:
      storage: 11Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-{{ include "ghost-k8s.name" . }}
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
