apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-ghost-content
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-{{ include "ghost-k8s.name" . }}
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
