apiVersion: v1
kind: Service
metadata:
  name: service-{{ include "ghost-k8s.name" . }}
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  ports:
  - port: 2368
    protocol: TCP
    targetPort: 2368
    name: ghk8s
  type: ClusterIP
  selector:
    app: {{ include "ghost-k8s.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: service-mysql-{{ include "ghost-k8s.name" . }}
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mysqlgh
  type: ClusterIP
  selector:
    app: mysql-{{ include "ghost-k8s.name" . }}


