apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-{{ include "ghost-k8s.name" . }}
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  serviceName: service-mysql-{{ include "ghost-k8s.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: mysql-{{ include "ghost-k8s.name" . }}
  template:
    metadata:
      labels:
        app: mysql-{{ include "ghost-k8s.name" . }}
        {{- include "ghost-k8s.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: mysql-{{ include "ghost-k8s.name" . }}-init
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        image: docker.io/busybox:stable-musl
        imagePullPolicy: Always
        command: ['sh', '-c', 'chown -R 999:999 /mnt/mysql || true'] 
        volumeMounts:
        - name: mysql-{{ include "ghost-k8s.name" . }}-volume
          mountPath: /mnt/mysql
          subPath: mysql-empty-dir
      containers:
      - name: mysql-{{ include "ghost-k8s.name" . }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
        image: docker.io/mysql:8.2
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mysql-{{ include "ghost-k8s.name" . }}
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1000m
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysqlgh
        volumeMounts:
        - name: mysql-{{ include "ghost-k8s.name" . }}-volume
          mountPath: /var/lib/mysql
          subPath: mysql-empty-dir
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: mysql-{{ include "ghost-k8s.name" . }}-volume
        persistentVolumeClaim:
          claimName: mysql-{{ include "ghost-k8s.name" . }}