apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost-k8s.name" . }}
  namespace: {{ include "ghost-k8s.name" . }}
  labels:
    {{- include "ghost-k8s.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: # copied from original manifests
      app: {{ include "ghost-k8s.name" . }}
      app.kubernetes.io/name: {{ include "ghost-k8s.name" . }}
      app.kubernetes.io/instance: {{ include "ghost-k8s.name" . }}
      app.kubernetes.io/version: "5.6"
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: {{ include "ghost-k8s.name" . }}

  template:
    metadata:
      namespace: {{ include "ghost-k8s.name" . }}
      labels: # copied from original manifests
        app: {{ include "ghost-k8s.name" . }}
        app.kubernetes.io/name: {{ include "ghost-k8s.name" . }}
        app.kubernetes.io/instance: {{ include "ghost-k8s.name" . }}
        app.kubernetes.io/version: "5.6"
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: {{ include "ghost-k8s.name" . }}
    spec:
      volumes:
      - name: {{ include "ghost-k8s.name" . }}-static-ghost
        persistentVolumeClaim:
          claimName: {{ include "ghost-k8s.name" . }}-static-ghost

      - name: ghost-config-prod
        secret:
          secretName: ghost-config-prod
          defaultMode: 420

      - name: tmp
        emptyDir:
          sizeLimit: 64Mi

      initContainers:
      - name: {{ include "ghost-k8s.name" . }}-init
        image: docker.io/busybox:stable-musl
        command:
        - /bin/sh
        - -c
        - chown -Rf 1000:1000 /var/lib/ghost/content || true

        volumeMounts:
        - name: {{ include "ghost-k8s.name" . }}-static-ghost
          mountPath: /var/lib/ghost/content


      containers:
      - name: {{ include "ghost-k8s.name" . }}
        image: ghcr.io/sredevopsorg/ghost-on-kubernetes:main
        ports:
        - name: ghk3s
          containerPort: 2368
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            path: /ghost/api/v4/admin/site/
            port: ghk3s
            httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              - name: Host
                value: {{ .Values.ingress.hostName }}

        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi

        volumeMounts:
        - name: {{ include "ghost-k8s.name" . }}-static-ghost
          mountPath: /var/lib/ghost/content
        - name: ghost-config-prod
          readOnly: true
          mountPath: /var/lib/ghost/config.production.json
          subPath: config.production.json
        - name: tmp # This is the temporary volume mount to allow loading themes
          mountPath: /tmp
          readOnly: false
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000

      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600

