apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ghost-k8s.name" . }}-ingress
  namespace: {{ include "ghost-k8s.name" . }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .Values.ingress.hostName }}
    secretName: spiritofbrogan-com-tls # todo refactor
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service-{{ include "ghost-k8s.name" . }}
            port:
              name: ghk8s
