apiVersion: v1
kind: Secret
metadata:
  name: mysql-ghost-k8s
  namespace: ghost-k8s
type: Opaque
stringData:
  MYSQL_DATABASE: mysql-db-name # Same as in config.production.json
  MYSQL_USER: mysql-db-user # Same as in config.production.json
  MYSQL_PASSWORD: mysql-db-password # Same as in config.production.json
  MYSQL_ROOT_PASSWORD: mysql-db-root-password # Same as in config.production.json

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: yourdomain-com-tls
#   namespace: ghost-k8s
# type: kubernetes.io/tls
# stringData:
#   tls.crt: content-tls-crt-base64 # Optional, if you want to use your own TLS certificate
#   tls.key: content-tls-key-base64 # Optional, if you want to use your own TLS certificate
