apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-k8s-static-ghost
  namespace: ghost-k8s
  labels:
    app: ghost-k8s
    app.kubernetes.io/name: ghost-k8s
    app.kubernetes.io/instance: ghost-k8s
    app.kubernetes.io/version: "5.6"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ghost-k8s
spec:
  storageClassName: microk8s-hostpath # enables automatic PV provisioning by microk8s
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  volumeName: pvc-7aa7e7b5-be0c-4231-a900-68913ccf7f34 # Added to existing cluster pv/pvc maintenance.
  resources:
    requests:
      storage: 11Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ghost-k8s
  namespace: ghost-k8s
  labels:
    app: mysql-ghost-k8s
    app.kubernetes.io/name: mysql-ghost-k8s
    app.kubernetes.io/instance: ghost-k8s
    app.kubernetes.io/version: "5.6"
    app.kubernetes.io/component: database-storage
    app.kubernetes.io/part-of: ghost-k8s
spec:
  storageClassName: microk8s-hostpath # enables automatic PV provisioning by microk8s
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
