apiVersion: v1
kind: Secret
metadata:
  name: mysql-ghost-k8s
  namespace: ghost-k8s
type: Opaque
stringData:
  # Same as in 04-config.production.yaml
  MYSQL_DATABASE: mysql_db
  MYSQL_USER: ghost
  MYSQL_PASSWORD: <example_password>
  MYSQL_ROOT_PASSWORD: <example_root_password>

---
apiVersion: v1
kind: Secret
metadata:
  name: example-com-tls
  namespace: ghost-k8s
type: kubernetes.io/tls
# base64 encoded strings of .crt and unencrypted .key files
data:
  tls.crt: example-base64-crt
  tls.key: example-base64-key
